### ISSUE TITLE
 java.lang.IndexOutOfBoundsException: index=2 length=2 capacity=0

### ISSUE THREAD

**Issue by VictorFrWu** [binance/binance-sbe-java-sample-app#1]
curl -X GET -H 'Accept: application/sbe' -H 'X-MBX-SBE: 1:0' 'https://api.binance.com/api/v3/exchangeInfo' | java -jar ./target/sbe-sample-app-1.0-SNAPSHOT.jar -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0curl: (6) Could not resolve host: application
curl: (3) URL rejected: Port number was not a decimal number between 0 and 65535
curl: (3) URL rejected: Port number was not a decimal number between 0 and 65535
Exception in thread "main" java.lang.IndexOutOfBoundsException: index=2 length=2 capacity=0
        at org.agrona.AbstractMutableDirectBuffer.boundsCheck0(AbstractMutableDirectBuffer.java:1716)
        at org.agrona.AbstractMutableDirectBuffer.getShort(AbstractMutableDirectBuffer.java:366)
        at spot_sbe.MessageHeaderDecoder.templateId(MessageHeaderDecoder.java:126)
        at com.binance.sbe.sbesampleapp.App.main(App.java:233)

**Comment by aisling-2** [comment]
@wuhewuhe The SBE is only available for Spot Testnet for now: `https://testnet.binance.vision/api/v3/exchangeInfo`

When it's available in the live exchange, it'll be announced here: https://github.com/binance/binance-spot-api-docs/blob/master/CHANGELOG.md
